// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaPnozo662H5u1hCiGM24LSQ0PaymbuTY',
    appId: '1:743910087774:web:a2f1c0b3d9e8b81354a8cf',
    messagingSenderId: '743910087774',
    projectId: 'workoutgym-e0b92',
    authDomain: 'workoutgym-e0b92.firebaseapp.com',
    storageBucket: 'workoutgym-e0b92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQskj9zIDSS_gQzlGxhw1E78wb2loq8Hg',
    appId: '1:743910087774:android:e948c42e80d0213654a8cf',
    messagingSenderId: '743910087774',
    projectId: 'workoutgym-e0b92',
    storageBucket: 'workoutgym-e0b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxyemhhr1zXujbtQsw35oywnySwNlTeZE',
    appId: '1:743910087774:ios:ae29e40bf367b12454a8cf',
    messagingSenderId: '743910087774',
    projectId: 'workoutgym-e0b92',
    storageBucket: 'workoutgym-e0b92.appspot.com',
    iosClientId: '743910087774-tthq6ofba753lnrbpch12gcubg0acsnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.workOutGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxyemhhr1zXujbtQsw35oywnySwNlTeZE',
    appId: '1:743910087774:ios:ae29e40bf367b12454a8cf',
    messagingSenderId: '743910087774',
    projectId: 'workoutgym-e0b92',
    storageBucket: 'workoutgym-e0b92.appspot.com',
    iosClientId: '743910087774-tthq6ofba753lnrbpch12gcubg0acsnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.workOutGym',
  );
}
